### ISSUE TITLE
Does it buy non-free limiteds?

### ISSUE THREAD

**Issue by eteche123** [J3ldo/UGC-Sniper#52]
sorry for publishing this on issues but im new at github.
i want to know if the bot buys non-free limiteds, asking bc i dont want to accidentally buy something with robux
thanks

**Comment by fallino11** [comment]
Don't worry, it won't.
When buying an item, the script permanently sets the "exceptecPrice" to 0, which is usually the price shown to the user, when trying to purchase something.
As soon roblox receives the request, roblox will check if the price was shown to the user correctly.
If that is not the case, and the product isn't free, roblox will automatically deny the purchase attempt.

For example:
If an item gets released, which is not set to free and lets say it costs 500 robux. The script will attempt to buy it anyways, since it was told to do that. The script will send a request to the roblox website, asking if you could purchase that item. The request includes information about, what kind of items you want, which currency you want to use (example: robux), what the price is (which is shown to the user) and who is buying the item.
(Feel free to read it by yourself: https://github.com/J3ldo/UGC-Sniper/blob/3ffd2314693b7fdb90882939e44d49d0b8b40ab4/main.py )
```python
34    data = {
35        "collectibleItemId": itemid,
36        "expectedCurrency": 1,
37        "expectedPrice": 0,
38        "expectedPurchaserId": user_id,
39        "expectedPurchaserType": "User",
40        "expectedSellerId": json["creatorTargetId"],
41        "expectedSellerType": "User",
42        "idempotencyKey": "random uuid4 string that will be your key or smthn",
43        "collectibleProductId": productid
44    }
```
After the roblox website receives that request, they will compare and check the datas to make sure everything is correct.
But in this case, the expected Datas is incorrect, since the actual price of the product is 500 robux. The roblox website will notice that and decline that purchase attempt and return an error message, saying that the "expectedPrice" is incorrect and should be fixed, if the user wants to buy that product. They also won't charge any robux.

**Comment by Ramune31** [comment]
when should you start running the code?

**Comment by eteche123** [comment]
> Don't worry, it won't. When buying an item, the script permanently sets the "exceptedPrice" to 0, which is usually the price shown to the user, when trying to purchase something. As soon roblox receives the request, roblox will check if the price was shown to the user correctly. If that is not the case, and the product isn't free, roblox will automatically deny the purchase attempt.
> 
> For example: An item gets released, which is not free and, lets say it costs 500 robux. The script will attempt to buy it anyways, since it was told to do that. The script will send a request to the roblox website, asking if you could purchase that item. The request includes information about, what kind of items you want, which currency you want to use (example: robux), what the price is (which is shown to the user) and who is buying the item. (Feel free to read it by yourself: https://github.com/J3ldo/UGC-Sniper/blob/3ffd2314693b7fdb90882939e44d49d0b8b40ab4/main.py )
> 
> ```python
> 34    data = {
> 35        "collectibleItemId": itemid,
> 36        "expectedCurrency": 1,
> 37        "expectedPrice": 0,
> 38        "expectedPurchaserId": user_id,
> 39        "expectedPurchaserType": "User",
> 40        "expectedSellerId": json["creatorTargetId"],
> 41        "expectedSellerType": "User",
> 42        "idempotencyKey": "random uuid4 string that will be your key or smthn",
> 43        "collectibleProductId": productid
> 44    }
> ```
> 
> After the roblox website receives that request, they will compare and check the datas to make sure everything is correct. But in this case, the expected Data is incorrect, since the actual price of the product is 500 robux. The roblox website will notice that and decline that purchase attempt and return an error message, saying that the "expectedPrice" is incorrect and should be fixed, if the user wants to buy that product. They also won't charge any robux.
> 
> **Because of that, there is no reason to be worried about. The script will NEVER purchase anything, which costs robux.**

wow tysm for the help dude really appreciate it :D
